server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: ORDER-SERVICE
          uri: lb://order-service
          predicates:
            - Path=/orders/**